### ISSUE TITLE
Chinese calendar `until` throws "mixed-sign values not allowed as duration fields" RangeError

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#2537]
Clearly this is a polyfill bug, but not sure if it reflects an underlying spec issue. Note that 2001 is a leap year in the chinese calendar that has an M04L leap month, so month 6 in 2001 is M05 while month 6 in 2000 is M06.

```js
// 2001 is a leap year
Temporal.PlainDate.from({ year: 2001, month: 6, day: 1, calendar: 'chinese' })
  .since({ year: 2000, month: 6, day: 1, calendar: 'chinese' }, { largestUnit: 'year' })
```

It throws a RangeError: 

```
ecmascript.mjs:3324 Uncaught RangeError: mixed-sign values not allowed as duration fields
    at Object.RejectDuration (ecmascript.mjs:3324:54)
    at new Duration (duration.mjs:47:8)
    at Calendar.dateUntil (calendar.mjs:165:12)
    at Object.Call (Call.js:19:9)
    at Object.CalendarDateUntil (ecmascript.mjs:1601:23)
    at Object.DifferenceTemporalPlainDate (ecmascript.mjs:3716:45)
    at Temporal.PlainDate.since (plaindate.mjs:136:15)
    at <anonymous>:2:4
```

**Comment by justingrant** [comment]
> if you can reproduce this with e.g. a leap day then a spec issue is more likely.

The problem turned out to be caused by a case that can never happen in the ISO calendar: when calculating the number of years between two dates where the years are different, the monthCodes are different, but the `month` is the same in both because the later date was after a leap month. 

So not a spec issue (until non-ISO math is specified, of course!).

Fix available in #2539.
