### ISSUE TITLE
cookbook: CI broken

### ISSUE THREAD

**Issue by ryzokuken** [tc39/proposal-temporal#792]
The cookbook CI pipeline is broken, we cannot merge any pull requests until it's fixed.

**Comment by gilmoreorless** [comment]
I noticed the cookbook tests started failing on `main` after my previous PR was merged in. I went digging to check if I'd inadvertently broken the builds, and found it's due to a change in Node version.

The tests passed when running Node 12.18.2: https://travis-ci.org/github/tc39/proposal-temporal/jobs/709512681
Then failed with 12.18.3: https://travis-ci.org/github/tc39/proposal-temporal/jobs/711951990

Digging further, it looks like the experimental module resolution system has changed between the two versions. Specifically, the `source` argument passed to the `transformSource` hook was previously a `string` (in 12.18.2) but is now a `Buffer` (in 12.18.13), so it doesn't get the `Temporal` import added to it.

Using a `console.log()` inside the `transformSource` hook of `polyfill/test/resolve.cookbook.mjs`:

```sh
$ TEST=absoluteFromLegacyDate nvm exec 12.18.2 npm run test-cookbook-one
Running node v12.18.2 (npm v6.14.5)

> proposal-temporal@0.3.0 test-cookbook-one /path/to/tc39/proposal-temporal/polyfill
> node --no-warnings --experimental-modules --icu-data-dir node_modules/full-icu --loader ./test/resolve.cookbook.mjs ../docs/cookbook/$TEST.mjs

[transformSource] {
  url: 'file:///path/to/tc39/proposal-temporal/docs/cookbook/absoluteFromLegacyDate.mjs',
  format: 'module',
  source: "const legacyDate = new Date('1970-01-01T00:00:01Z');\n" +
    '\n' +
    '// Convert legacy Date to Temporal.Absolute\n' +
    'const absolute = Temporal.Absolute.fromEpochMilliseconds(legacyDate.getTime());\n' +
    '\n' +
    'assert(absolute instanceof Temporal.Absolute);\n'
}

##############

$ TEST=absoluteFromLegacyDate nvm exec 12.18.3 npm run test-cookbook-one
Running node v12.18.3 (npm v6.14.6)

> proposal-temporal@0.3.0 test-cookbook-one /path/to/tc39/proposal-temporal/polyfill
> node --no-warnings --experimental-modules --icu-data-dir node_modules/full-icu --loader ./test/resolve.cookbook.mjs ../docs/cookbook/$TEST.mjs

[transformSource] {
  url: 'file:///path/to/tc39/proposal-temporal/docs/cookbook/absoluteFromLegacyDate.mjs',
  format: 'module',
  source: <Buffer 63 6f 6e 73 74 20 6c 65 67 61 63 79 44 61 74 65 20 3d 20 6e 65 77 20 44 61 74 65 28 27 31 39 37 30 2d 30 31 2d 30 31 54 30 30 3a 30 30 3a 30 31 5a 27 ... 176 more bytes>
}
file:///path/to/tc39/proposal-temporal/docs/cookbook/absoluteFromLegacyDate.mjs:4
const absolute = Temporal.Absolute.fromEpochMilliseconds(legacyDate.getTime());
                 ^

ReferenceError: Temporal is not defined
    at file:///path/to/tc39/proposal-temporal/docs/cookbook/absoluteFromLegacyDate.mjs:4:18
    at ModuleJob.run (internal/modules/esm/module_job.js:139:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```
